
version: '3'

services:
  postgres:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    networks:
      - databased
    volumes:
      - /var/lib/postgresql/data/:/var/lib/postgresql/data/

networks: 
  databased:
    external: true
