version: '3.7'

services:
  traefik:
    image: traefik:v2.7
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
      - target: 8080
        published: 10000
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/traefik/acme/acme.json:/acme.json 
    networks:
      - proxy
    deploy:
      labels:
        - traefik.enable=false

    command:
      - --api=true
      - --api.insecure=true
      - --providers.docker
      - --providers.docker.swarmmode=true
      - --providers.docker.network=proxy
      - --entrypoints.http=true
      - --entrypoints.http.address=:80
      - --entrypoints.http.http.tls=false
      - --entrypoints.https=true
      - --entrypoints.https.address=:443
      - --entrypoints.https.http.tls
      - --certificatesresolvers.letsencrypt
      - --certificatesresolvers.letsencrypt.acme.httpchallenge
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=http
      - --certificatesresolvers.letsencrypt.acme.email=valk@randomairborne.dev
      
networks:
  proxy:
    external: true
